### ISSUE TITLE
Keyboard Inputs accepted.

### ISSUE THREAD

**Issue by matthewsphillips** [ftiff/SplashBuddy#34]
I noticed that user can still "command + tab" to switch apps in the background. Then send keyboard commands to that App while Splash Buddy is in front and fullscreen. This does not seem like expected behaviour. I understand the need to be able to quit the app with a keyboard shortcut. But, once a fully functional process is tested, Quit could be removed in a production environment. Or if ignore all keyboard inputs is implemented then have a secret click that can quit the app, like most Kiosk Apps.
Also, user can still move mouse over Dock and Hot Corners work when App is Fullscreen.

**Comment by ftiff** [comment]
Hi Matthews,

I've made the required changes in d257010
It will be part of RC5, due soon. If you can, please test! 

Thanks,
François
