### ISSUE TITLE
Allow customization of "Welcome to your Mac" and subtitle.

### ISSUE THREAD

**Issue by rudyca** [ftiff/SplashBuddy#36]
I would like to be able to customize the Welcome title and subtitle to fit within our environment.
<img width="523" alt="customize welcome title" src="https://user-images.githubusercontent.com/3607322/28032887-2073fec2-657a-11e7-85af-285d26330951.png">

**Comment by rudyca** [comment]
Awesome!! Looking forward to the release and give it a try.

Thank you.

**Comment by ftiff** [comment]
Not needed anymore with 1.1 :)
More on that soon
