### ISSUE TITLE
Form HTML gets displayed if app gets relaunched

### ISSUE THREAD

**Issue by cybertunnel** [ftiff/SplashBuddy#41]
The `form.html` file gets displayed if form input was already submitted.

Would be nice if the computer is able to reboot and not display the `form.html` file if the information was asked for once already.

**Comment by ftiff** [comment]
Perhaps do a .SplashBuddyFormDone ? :)

**Comment by matthewsphillips** [comment]
What version works with writing a .SplashBuddyFormDone file?  I've only had success by renaming the form.html once the info is present so that it won't get used on next launch.

**Comment by ftiff** [comment]
Tyler, can you have a look at this while you're working on forms? Thank you :)

**Comment by cybertunnel** [comment]
Sure thing, just got my Xcode updated so able to work on it now.

**Comment by cybertunnel** [comment]
Fixed on the current userinput branch.
