### ISSUE TITLE
Failure message does not update.

### ISSUE THREAD

**Issue by matthewsphillips** [ftiff/SplashBuddy#42]
The Jelly color changes to Red when jamf.log reports "Installation failed. The installer reported: installer: Package name is..."
Then "(AppName) failed to install. Support has been notified." is displayed in Red at the bottom of the window.

If the pkg is reinstalled successfully while splash buddy is running, the Jelly turns Green once the install succeeds. However, the Error Message in red at the bottom is not cleared. This is not accurate or desired.

**Comment by ftiff** [comment]
Hi Matt, it is solved in master but not yet in 1.1
