### ISSUE TITLE
Option to remove/hide Continue button

### ISSUE THREAD

**Issue by grahampugh** [ftiff/SplashBuddy#6]
It would be good if the Continue button could be hidden, either automatically if all canContinue keys are set to false, or manually with a key.  In our case we reboot the machine when the kickstart script is finished, so a continue button is superfluous.

**Comment by ftiff** [comment]
Thanks Graham!

Will do!

**Comment by ftiff** [comment]
Hi Graham,

I've started working on it. 

What would be the action at the end? Have a 5 second timer to give the user the possibility to read the message at the bottom of the window? "All software were installed" / "A software failed to install. Support has been notified"

**Comment by grahampugh** [comment]
H François,

I would say just go onto the post install script automatically (or quit if none exists). 

Cheers, Graham 

Von meinem iPhone gesendet

**Comment by smithjw** [comment]
For my usage I'd like to hide the Continue button as I quit SB and manage logging the user out from my enrolment script that runs from Jamf directly.

In the meantime, I've added an item to the sidebar marked as required but doesn't actually have a package attached so the Continue button is always greyed out

**Comment by ftiff** [comment]
This will be in 1.1. 
Thank you for your report!
